const PEOPLE = {
  p1: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=360&q=80",
  p2: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=360&q=80",
  p3: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=360&q=80",
  p4: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=360&q=80",
  p5: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=360&q=80",
};

const BANNERS = {
  leadership: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1400&q=80",
  tech: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=80",
  volunteering: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1400&q=80",
  media: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=1400&q=80",
  stage: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1400&q=80",
};

const makeLeaders = (prefix) => ({
  president: { image: PEOPLE.p1, name: `${prefix} President`, designation: "President" },
  vicePresident: { image: PEOPLE.p2, name: `${prefix} Vice President`, designation: "Vice President" },
  secretary: { image: PEOPLE.p3, name: `${prefix} Secretary`, designation: "Secretary" },
  treasurer: { image: PEOPLE.p4, name: `${prefix} Treasurer`, designation: "Treasurer" },
});

const makeMembers = (prefix) => [
  { image: PEOPLE.p1, name: `${prefix} Member 01`, role: "Committee Lead" },
  { image: PEOPLE.p2, name: `${prefix} Member 02`, role: "Operations Coordinator" },
  { image: PEOPLE.p3, name: `${prefix} Member 03`, role: "Events Coordinator" },
  { image: PEOPLE.p4, name: `${prefix} Member 04`, role: "Design Coordinator" },
  { image: PEOPLE.p5, name: `${prefix} Member 05`, role: "Community Relations" },
  { image: PEOPLE.p2, name: `${prefix} Member 06`, role: "Logistics Coordinator" },
];

const makeEvents = (clubName, banner) => [
  {
    id: 1,
    title: `${clubName} Welcome Drive`,
    date: "Apr 12, 2026",
    description: "Kick-off networking and orientation for new student members.",
    image: banner,
  },
  {
    id: 2,
    title: `${clubName} Signature Forum`,
    date: "May 08, 2026",
    description: "Skill-building sessions and collaborative discussions.",
    image: banner,
  },
  {
    id: 3,
    title: `${clubName} Community Impact Day`,
    date: "Jun 01, 2026",
    description: "Club-led outreach and impact activities across campus.",
    image: banner,
  },
];

export const CLUBS = [
  {
    id: "rotaract-club",
    name: "Rotaract Club",
    color: "#ef4444",
    logo: BANNERS.volunteering,
    banner: BANNERS.volunteering,
    description: "Service-driven student club focused on social impact and leadership development.",
    mission: "Empower students to create measurable community impact through service and collaboration.",
    leadership: makeLeaders("Rotaract"),
    members: makeMembers("Rotaract"),
    events: makeEvents("Rotaract Club", BANNERS.volunteering),
  },
  {
    id: "gavel-club",
    name: "The Gavel Club",
    color: "#f59e0b",
    logo: BANNERS.leadership,
    banner: BANNERS.leadership,
    description: "Public speaking and leadership communication club for confident student voices.",
    mission: "Build confident communicators and ethical leaders.",
    leadership: makeLeaders("Gavel"),
    members: makeMembers("Gavel"),
    events: makeEvents("The Gavel Club", BANNERS.leadership),
  },
  {
    id: "gaming-community",
    name: "SLIIT Gaming Community",
    color: "#8b5cf6",
    logo: BANNERS.tech,
    banner: BANNERS.tech,
    description: "Competitive and casual gaming culture with tournaments and esports collaboration.",
    mission: "Create a healthy, innovative esports and gaming ecosystem.",
    leadership: makeLeaders("Gaming Community"),
    members: makeMembers("Gaming Community"),
    events: makeEvents("SLIIT Gaming Community", BANNERS.tech),
  },
  {
    id: "aiesec",
    name: "SLIIT AIESEC",
    color: "#2563eb",
    logo: BANNERS.leadership,
    banner: BANNERS.leadership,
    description: "Global youth leadership network focused on cultural exchange and growth.",
    mission: "Develop global citizens through leadership experiences.",
    leadership: makeLeaders("AIESEC"),
    members: makeMembers("AIESEC"),
    events: makeEvents("SLIIT AIESEC", BANNERS.leadership),
  },
  {
    id: "leo-club",
    name: "SLIIT LEO Club",
    color: "#f97316",
    logo: BANNERS.volunteering,
    banner: BANNERS.volunteering,
    description: "Student volunteers leading service projects and social welfare campaigns.",
    mission: "Serve local communities through youth-driven leadership.",
    leadership: makeLeaders("LEO Club"),
    members: makeMembers("LEO Club"),
    events: makeEvents("SLIIT LEO Club", BANNERS.volunteering),
  },
  {
    id: "foc-media-unit",
    name: "SLIIT Faculty Of Computing Media Unit",
    color: "#0ea5e9",
    logo: BANNERS.media,
    banner: BANNERS.media,
    description: "Media storytelling team covering computing faculty events and campaigns.",
    mission: "Capture and amplify faculty innovation stories.",
    leadership: makeLeaders("FOC Media Unit"),
    members: makeMembers("FOC Media Unit"),
    events: makeEvents("FOC Media Unit", BANNERS.media),
  },
  {
    id: "foe-media-unit",
    name: "SLIIT Faculty Of Engineering Media Unit",
    color: "#eab308",
    logo: BANNERS.media,
    banner: BANNERS.media,
    description: "Engineering media team delivering visual coverage and technical storytelling.",
    mission: "Promote engineering achievements through quality media output.",
    leadership: makeLeaders("FOE Media Unit"),
    members: makeMembers("FOE Media Unit"),
    events: makeEvents("FOE Media Unit", BANNERS.media),
  },
  {
    id: "ieee-student-branch",
    name: "IEEE Student Branch of SLIIT",
    color: "#1d4ed8",
    logo: BANNERS.tech,
    banner: BANNERS.tech,
    description: "Technology-focused student branch hosting workshops, hackathons, and industry sessions.",
    mission: "Advance technology for humanity through student innovation.",
    leadership: makeLeaders("IEEE Student Branch"),
    members: makeMembers("IEEE Student Branch"),
    events: makeEvents("IEEE Student Branch", BANNERS.tech),
  },
  {
    id: "engineering-research-innovation",
    name: "SLIIT Engineering Research and Innovation Club",
    color: "#14b8a6",
    logo: BANNERS.tech,
    banner: BANNERS.tech,
    description: "Research and innovation hub for prototypes, papers, and multidisciplinary projects.",
    mission: "Drive practical innovation through collaborative research.",
    leadership: makeLeaders("Engineering R&I Club"),
    members: makeMembers("Engineering R&I Club"),
    events: makeEvents("Engineering R&I Club", BANNERS.tech),
  },
  {
    id: "art-circle",
    name: "Art Circle SLIIT",
    color: "#ec4899",
    logo: BANNERS.stage,
    banner: BANNERS.stage,
    description: "Creative collective for visual arts, design showcases, and collaborative expression.",
    mission: "Cultivate artistic expression and creative confidence.",
    leadership: makeLeaders("Art Circle"),
    members: makeMembers("Art Circle"),
    events: makeEvents("Art Circle SLIIT", BANNERS.stage),
  },
  {
    id: "drama-society",
    name: "SLIIT Drama Society",
    color: "#a855f7",
    logo: BANNERS.stage,
    banner: BANNERS.stage,
    description: "Performance arts society organizing theater productions and acting workshops.",
    mission: "Inspire storytelling, performance, and stage confidence.",
    leadership: makeLeaders("Drama Society"),
    members: makeMembers("Drama Society"),
    events: makeEvents("SLIIT Drama Society", BANNERS.stage),
  },
  {
    id: "student-chapter",
    name: "SLIIT Student Chapter",
    color: "#22c55e",
    logo: BANNERS.leadership,
    banner: BANNERS.leadership,
    description: "Student chapter focused on peer learning, projects, and leadership opportunities.",
    mission: "Support student growth through chapter-based collaboration.",
    leadership: makeLeaders("Student Chapter"),
    members: makeMembers("Student Chapter"),
    events: makeEvents("SLIIT Student Chapter", BANNERS.leadership),
  },
];
